{"name": "测试数据：【 测试test，123456，False，1003，用户名不存在】", "status": "failed", "statusDetails": {"message": "AssertionError: assert 100017 == 1003", "trace": "self = <testcases.api_test.test_03_login.TestUserLogin object at 0x04971AF0>\nusername = '测试test', password = '123456', except_result = False\nexcept_code = 1003, except_msg = '用户名不存在'\n\n    @allure.story(\"用例--登录用户\")\n    @allure.description(\"该用例是针对获取用户登录接口的测试\")\n    @allure.issue(\"http://10.5.15.116/#/home\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"暂无\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"测试数据：【 {username}，{password}，{except_result}，{except_code}，{except_msg}】\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"username, password, except_result, except_code, except_msg\",\n                             api_data[\"test_login_user\"])\n    def test_login_user(self, username, password, except_result, except_code, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = login_user(username, password)\n        step_1(username)\n        assert result.success == except_result, result.error\n        assert result.response.status_code == 200\n        assert result.success == except_result, result.error\n        logger.info(\"code ==>> 期望结果：{}， 实际结果：【 {} 】\".format(except_code, result.response.json()[\"code\"]))\n        print(except_code)\n>       assert result.response.json()[\"code\"] == except_code\nE       assert 100017 == 1003\n\ntest_03_login.py:35: AssertionError"}, "description": "该用例是针对获取用户登录接口的测试", "steps": [{"name": "步骤1 ==>> 登录用户", "status": "passed", "parameters": [{"name": "username", "value": "'测试test'"}], "start": 1622553141417, "stop": 1622553141417}], "attachments": [{"name": "log", "source": "46c00f9d-1087-4b65-8261-fa4569afa5ca-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "07b49864-926e-4125-a8f0-6122f73edddd-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "b161277e-93cc-4e92-9d91-f1169a17213e-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'测试test'"}, {"name": "password", "value": "'123456'"}, {"name": "except_result", "value": "False"}, {"name": "except_code", "value": "1003"}, {"name": "except_msg", "value": "'用户名不存在'"}], "start": 1622553141399, "stop": 1622553141420, "uuid": "a2d5d14b-7559-4970-9870-be32a6f7998d", "historyId": "56bfc4b39b0fa959e074da77d0878485", "testCaseId": "7272db244dabef390096479ae3196642", "fullName": "testcases.api_test.test_03_login.TestUserLogin#test_login_user", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "用户登录模块"}, {"name": "story", "value": "用例--登录用户"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_03_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "LAPTOP-1UC29CD2"}, {"name": "thread", "value": "15788-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_03_login"}], "links": [{"type": "test_case", "url": "暂无", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "http://10.5.15.116/#/home", "name": "点击，跳转到对应BUG的链接地址"}]}