{"name": "测试数据：【 测试test，True，0，删除用户信息成功 】", "status": "broken", "statusDetails": {"message": "AttributeError: 'NoneType' object has no attribute 'get'", "trace": "self = <testcases.api_test.test_05_delete_user.TestUserDelete object at 0x04852510>, login_fixture = {'code': 100010, 'data': 'failed', 'message': '系统内部错误'}, username = '测试test', except_result = True, except_code = 0, except_msg = '删除用户信息成功'\n\n    @allure.story(\"用例--删除用户信息\")\n    @allure.description(\"该用例是针对获取用户删除接口的测试\")\n    @allure.issue(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"测试数据：【 {username}，{except_result}，{except_code}，{except_msg} 】\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"username, except_result, except_code, except_msg\",\n                             api_data[\"test_delete_user\"])\n    @pytest.mark.usefixtures(\"insert_delete_user\")\n    def test_delete_user(self, login_fixture, username, except_result, except_code, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        user_info = login_fixture\n>       admin_user = user_info.get(\"login_info\").get(\"username\")\nE       AttributeError: 'NoneType' object has no attribute 'get'\n\ntestcases\\api_test\\test_05_delete_user.py:36: AttributeError"}, "description": "该用例是针对获取用户删除接口的测试", "attachments": [{"name": "log", "source": "f9a6a994-b247-4077-8a32-f74405f3c4b5-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "4bf4fc90-3d52-4681-b536-3eb35490be72-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'测试test'"}, {"name": "except_result", "value": "True"}, {"name": "except_code", "value": "0"}, {"name": "except_msg", "value": "'删除用户信息成功'"}], "start": 1622548081184, "stop": 1622548081186, "uuid": "6f0840f4-b4b5-4107-ad20-811d7fbb7d9b", "historyId": "da319e4398ddda3c7eb597b8bd4ec2fc", "testCaseId": "f140003f8969cec64326a77ad093297e", "fullName": "testcases.api_test.test_05_delete_user.TestUserDelete#test_delete_user", "labels": [{"name": "story", "value": "用例--删除用户信息"}, {"name": "feature", "value": "用户删除模块"}, {"name": "severity", "value": "normal"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "tag", "value": "single"}, {"name": "tag", "value": "@pytest.mark.usefixtures('insert_delete_user')"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_05_delete_user"}, {"name": "subSuite", "value": "TestUserDelete"}, {"name": "host", "value": "LAPTOP-1UC29CD2"}, {"name": "thread", "value": "3028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_05_delete_user"}], "links": [{"type": "test_case", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应BUG的链接地址"}]}